# Generated by Django 5.1.6 on 2026-01-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='venue',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue_address',
            field=models.TextField(default='Unknown Address', help_text='Enter the address of the venue'),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue_name',
            field=models.CharField(default='Unknown Venue', help_text='Enter the name of the venue', max_length=200),
        ),
    ]
