# Generated by Django 5.1.6 on 2026-01-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_venue_booking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='venue_address',
            field=models.TextField(help_text='Enter the address of the venue'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='venue_name',
            field=models.CharField(help_text='Enter the name of the venue', max_length=200),
        ),
    ]
